### ISSUE TITLE
Cannot update reachability on non-bridged accessory! with latest version of Homebridge v1.0.2 (2020-04-28)

### ISSUE THREAD

**Issue by Gordon-Newell** [jamesrodda/homebridge-mihomegateway#7]
I have just updated my Homebridge server and now the system errors whenever I boot with the homebridge-mihomegateway config included

[4/28/2020, 16:22:28] Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:399:13)
    at PlatformAccessory.updateReachability (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:124:34)
    at MiHomeAccessory.updateReachability (/usr/lib/node_modules/homebridge-mihomegateway/index.js:261:18)
    at new MiHomeAccessory (/usr/lib/node_modules/homebridge-mihomegateway/index.js:238:8)
    at MiHomeGateway.addAccessory (/usr/lib/node_modules/homebridge-mihomegateway/index.js:107:38)
    at MiHomeGateway.addDevice (/usr/lib/node_modules/homebridge-mihomegateway/index.js:74:10)
    at MiHomeGateway.<anonymous> (/usr/lib/node_modules/homebridge-mihomegateway/index.js:57:16)
    at Request.self.callback (/usr/lib/node_modules/homebridge-mihomegateway/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-mihomegateway/node_modules/request/request.js:1154:10)

**Comment by jamesrodda** [comment]
Hi,

Firstly, didn't even know Homebridge was hitting v1.0! Looks like `updateReachability` has been removed. I'll get this sorted.

Thanks for the heads-up.

James
